### ISSUE TITLE
Completely wrong introduciton of Cradle

### ISSUE THREAD

**Issue by WeihaoTan** [ulab-uiuc/AGI-survey#6]
Hi, I attended ICLR this year and I really appreciated the organizer's effort for such a well-organized and insightful workshop. 

However, as one of the authors of the paper, [Towards General Computer Control: A Multimodal Agent for Red Dead Redemption II as a Case Study](https://arxiv.org/abs/2403.03186), I found its introduction is completely wrong in the survey, which is extremely disappointing. 

Here is the description shown in your survey in page 22:
"In the gaming realm, agents have been deployed in simulated interactive environments, including Minecraft (Wang et al., 2023h;b), Starcraft II (Ma et al., 2023b), and Red Dead Redemption (Tan et al., 2024). These agents receive textual observations from internal APIs and execute predefined semantic actions.  However, these domain-specific
applications limit the agents’ ability to generalize to other games or broader software applications."

I cannot believe there are 3 mistakes within the first two sentences.
1. We played Red Dead Redemption **II**, instead of Red Dead Redemption.
2. RDR2 is a 3A closed-source commercial game, there is no way to get the textual observations with the internal APIs, which is one of the most important reasons for us to choose this game. No Cheating! We even already mentioned it in our title, we are a multimodal agent. We directly use the screenshot of the game as input and output keyboard and mouse actions, which is the same as people do.  
3. We use GPT-4V to generate keyboard and mouse level atomic skills according to the in-game instructions instead of relying on predefined actions.
4. We are a general framework towards general computer control. We have extended the framework to multiple games and software and will release a new report next month. 

I would recommend that the authors should take a deep look at our paper, at least the title...

**Comment by ImKeTT** [comment]
Hi @WeihaoTan, we appreciate your insightful suggestions and corrections, especially regarding the agent section.
The Cradle is an impressive work with no doubt, and you've absolutely caught some parts where we can improve our paper. We'll be sure to incorporate your corrections and update the arxiv version as soon as possible.

As an ongoing open-source project with a lot of moving parts, we understand that some mistakes can slip through. We deeply value constructive feedback and corrections from the community, and we always strive for a **collaborative and inclusive approach** :)
