### ISSUE TITLE
Reversed chronoligical order is better?

### ISSUE THREAD

**Issue by PengjuYan** [ulab-uiuc/AGI-survey#7]
I suggest order list in a way that most recent ones appear first. Then people don't have to scroll to the end of each section to get new papers.

**Comment by lwaekfjlk** [comment]
make sense cc @Kunlun-Zhu

**Comment by Kunlun-Zhu** [comment]
Thank you for your suggestion, @PengjuYan . We understand the convenience of having the most recent papers appear first, but we believe that maintaining a chronological order (from oldest to newest) offers several key benefits:

##Historical Context:
Chronological order helps readers understand the development and progression of ideas over time. By following the sequence in which papers were published, readers can see how research has evolved, which methodologies were built upon, and what foundational work has influenced more recent studies.
##Structured Learning:
For new readers or those unfamiliar with the topic, starting from the beginning provides a structured learning path. It allows for a gradual build-up of knowledge, starting with fundamental concepts and leading up to the latest advancements.
##Citation and Reference:
Often, newer papers cite older research. Reading in chronological order allows for a smoother understanding of these references, as readers encounter the foundational work first and then see how it is applied or built upon in later studies.
##Consistency:
Chronological order is a widely accepted standard in academic and research contexts. It aligns with how bibliographies, literature reviews, and historical analyses are typically structured, ensuring consistency and ease of use for a broad audience.

While we appreciate the efficiency that reversed chronological order offers for finding the latest updates, we feel that chronological order ultimately supports a deeper and more comprehensive understanding of the research landscape.

Thank you for your feedback, and we hope this explanation clarifies our reasoning.

**Comment by chuanyangjin** [comment]
Thanks for the suggestion. In each subsection, we now display only around 20 selected impactful papers discussed in our survey. Therefore, I believe it is easy to find the most recent papers at the end.

**Comment by PengjuYan** [comment]
Thank you guys! Looks like I have no reason not to close this issue.
